### ISSUE TITLE
.es6 编译后 html中引入文件发转换

### ISSUE THREAD

**Issue by fukai007** [fex-team/fis-parser-babel-5.x#10]
编译前

```
    <script src="./js/TweenMax.min.js"></script>
    <scirpt src='./js/ttf.es6'></scirpt>
    <script src="./js/ttt.js" charset="utf-8"></script>
```

编译后

```
    <script src="/static/js/TweenMax.min.js"></script>
    <scirpt src='./js/ttf.es6'></scirpt>  <!--ttf.es6文件没有被更换-->
    <script src="/static/js/ttt.js" charset="utf-8"></script>
```

配置文件

fis.match('*.es6', {
  // fis-optimizer-uglify-js 插件进行压缩，已内置
  parser: fis.plugin('babel-5.x', {
      blacklist: ['regenerator'],
      stage: 3
  }),
  rExt: 'js',
  optimizer: fis.plugin('uglify-js')
});

// 清除其他配置，只保留如下配置-2016-07-18 21:33-miles_fk
fis.match('*.js', {
  // fis-optimizer-uglify-js 插件进行压缩，已内置
  optimizer: fis.plugin('uglify-js')
});

fis.match('*.css', {
  // fis-optimizer-clean-css 插件进行压缩，已内置
  optimizer: fis.plugin('clean-css')
});

fis.match('*.png', {
  // fis-optimizer-png-compressor 插件进行压缩，已内置
  optimizer: fis.plugin('png-compressor')
});

fis.match('*.{png,js,css,es6}', {
    release: '/static/$0'
});

**Comment by hefangshi** [comment]
文件路径引用错误，FIS没有找到这个文件。
