### ISSUE TITLE
blacklist: ['useStrict']无效

### ISSUE THREAD

**Issue by Capricair** [fex-team/fis-parser-babel-5.x#15]
不想让babel添加全局的 use strict，网上查了这个方式可以解决，但在此插件中设置并没有起作用，请问此插件如何设置？
![image](https://cloud.githubusercontent.com/assets/6244446/18375024/b6b9c104-7684-11e6-85c2-f003a1568176.png)

**Comment by hefangshi** [comment]
应该已经解决了？options一级需要去掉
