### ISSUE TITLE
html编译不支持<script type="text/babel">？

### ISSUE THREAD

**Issue by codering** [fex-team/fis-parser-babel-5.x#5]
才开始接触reactjs, 看了下fis3-demo中的use-react, 在index2.html中将`<script> type改成"text/babel"` 就无法编译了。是不支持还是需要设置什么？

**Comment by codering** [comment]
@hefangshi ？

**Comment by hefangshi** [comment]
这是FIS的内嵌编译的语法规范。 `text/x-jsx` 表示内部的内容使用 jsx 语法编译

**Comment by codering** [comment]
@hefangshi  我看到[http://www.tuicool.com/articles/NFvYfeB](http://www.tuicool.com/articles/NFvYfeB)
说现在的标准改成了text/babel, fis能否支持下呢？

**Comment by hefangshi** [comment]
```
fis.match('**.html', {
    preprocessor: function (content, file) {
        return content.replace(/text\/babel/g, 'text/x-jsx');
    } 
});
```

可以自己简单的处理下。

`text/x-ext` 这种是 FIS 内置的语法规范，是表示会把内部的内容按照指定后缀名去处理，而不是某种语言具体的规范。

**Comment by codering** [comment]
@hefangshi  恩，明白了，谢谢！
