### ISSUE TITLE
问个babel转换箭头函数的问题

### ISSUE THREAD

**Issue by codering** [fex-team/fis-parser-babel-5.x#6]
``` js
class CommentForm extends Component {

    testFn = (e) => {

    }
}
```

转换错误
parser.babel-5.x: /app.jsx: Unexpected token (78:11) [/home/coding/workspace/app.jsx]  

es6转换成es5不支持吗？

**Comment by hefangshi** [comment]
造成报错的不是箭头函数，而是你使用的是 `es7.classProperties`

这个功能只有配置 stage: 0 才会生效，stage-0 功能的使用请慎重，因为 stage-0 意味着不一定被未来的规范吸收。

所以你应该这样写

``` javascript
class CommentForm extends Component {
    testFn (e) {
    }
}
```

凡是 Babel 5.x 的功能， fis-parser-babel-5.x 都支持，所以出现问题，请先研究清楚 Babel 5.x 的文档 https://developit.github.io/babel-legacy-docs//docs/usage/experimental/
