### ISSUE TITLE
哪里设置babel插件babel-plugin-transform-es2015-classes？

### ISSUE THREAD

**Issue by codering** [fex-team/fis-parser-babel-5.x#7]
感觉这个插件配置文档说的不是很清除啊，看了下源码也不知道怎么读取配置的

**Comment by hefangshi** [comment]
首先，这个插件是 babel 5.x，因此根本没有所谓的 `babel-plugin-transform-es2015-classes`

其次，文档说的很清楚，babel 5.x 的文档去 https://developit.github.io/babel-legacy-docs 看，提供给插件的参数就是文档 https://developit.github.io/babel-legacy-docs//docs/usage/options/ 中的参数。

最后，你的需求应该默认就满足，es6.classes属于默认开启的Transform，https://developit.github.io/babel-legacy-docs//docs/advanced/transformers/ 除非你希望要的功能根本就不叫这个名字。

我们不可能把整个babel的文档都搬到插件里面来，还请去babel的官网看看。

**Comment by codering** [comment]
sorry, babel配置还在学习中。
顺便说下 https://developit.github.io/babel-legacy-docs/ 里的详细说明的超链接都是失效的，需要加上'babel-legacy-docs' , 如  https://developit.github.io/docs/learn-es2015/#classes  改成 https://developit.github.io/babel-legacy-docs/docs/learn-es2015/#classes
